// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID         uuid.UUID
	ExpiryDate time.Time
	UserID     int32
	CreatedAt  time.Time
	ModifiedAt pgtype.Timestamptz
}

type Speedcamera struct {
	ID                  int32
	Latitude            pgtype.Numeric
	Longitude           pgtype.Numeric
	Type                int32
	SpeedLimit          pgtype.Int4
	DirectionType       pgtype.Int4
	Direction           pgtype.Int4
	LocationDescription pgtype.Text
	Source              int32
	Expiration          pgtype.Timestamptz
	CreatedBy           pgtype.Int4
	CreatedAt           time.Time
	ModifiedAt          pgtype.Timestamptz
}

type SpeedcamerasSource struct {
	ID   int32
	Name string
}

type SpeedcamerasType struct {
	ID   int32
	Name string
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	ModifiedAt   pgtype.Timestamptz
}

type UserVote struct {
	ID            int32
	UserID        int32
	SpeedcameraID int32
	VoteType      string
	CreatedAt     time.Time
	ModifiedAt    pgtype.Timestamptz
}
