// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID         int32
	Token      string
	ExpiryDate pgtype.Timestamp
	UserID     int32
	CreatedAt  pgtype.Timestamp
	ModifiedAt pgtype.Timestamp
}

type Speedcamera struct {
	ID                  int32
	Latitude            pgtype.Numeric
	Longitude           pgtype.Numeric
	Type                int32
	SpeedLimit          pgtype.Int4
	DirectionType       pgtype.Int4
	Direction           pgtype.Int4
	LocationDescription pgtype.Text
	Source              int32
	Expiration          pgtype.Timestamp
	CreatedBy           pgtype.Int4
	CreatedAt           pgtype.Timestamp
	ModifiedAt          pgtype.Timestamp
}

type SpeedcamerasSource struct {
	ID   int32
	Name string
}

type SpeedcamerasType struct {
	ID   int32
	Name string
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	ModifiedAt   pgtype.Timestamp
}

type UserVote struct {
	ID            int32
	UserID        int32
	SpeedcameraID int32
	VoteType      string
	CreatedAt     pgtype.Timestamp
	ModifiedAt    pgtype.Timestamp
}
